dist: trusty
sudo: false
env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"
after_success:
  "curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {index.html}  ftp://ftp.netzone.ch/"

